//GET http://localhost:8080/contacts


//POST http://localhost:8080/contacts HTTP/1.1 
//content-type: application/json
//
//{
//    "firstName": "Harry",
//    "lastName": "Potter",
//    "email": "wizardHarryP@gmagic.com",
//    "favoriteColor": "red",
//    "birthday": "1980-07-31"
//}

//PUT http://localhost:8080/contacts/65b332884dac9a088dc2eb74 HTTP/1.1 
//content-type: application/json
//    
//{
//    "firstName": "Tony",
//    "lastName": "Stark",
//    "email": "tonystark@rich.com",
//    "favoriteColor": "red",
//    "birthday": "1970-05-29"
//}

//DELETE http://localhost:8080/contacts/65b332884dac9a088dc2eb74



//*******OnRender*******//

GET https://cse341kjm.onrender.com/contacts


//POST https://cse341kjm.onrender.com/contacts HTTP/1.1 
//content-type: application/json
//
//{
//    "firstName": "Princess",
//    "lastName": "Peach",
//    "email": "Peachespeachespeaches@bros.com",
//    "favoriteColor": "pink",
//    "birthday": "1980-07-31"
//}

//PUT https://cse341kjm.onrender.com/contacts/
//content-type: application/json
//    
//{
//    "firstName": "Tony",
//    "lastName": "Stark",
//    "email": "tonystark@rich.com",
//    "favoriteColor": "red",
//    "birthday": "1970-05-29"
//}

//DELETE https://cse341kjm.onrender.com/contacts/65b1c97a987d426fe9cf8830
